# Generated by Django 5.0.7 on 2024-07-22 07:41
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
    ]
